### ISSUE TITLE
Inproper error message when export

### ISSUE THREAD

**Issue by sungmanc** [open-edge-platform/training_extensions#2150] opened 2023-05-15 06:09 UTC
**Describe the bug**

When I didn't use the `workspace` and didn't input the `template.yaml` file, the expected error message is `Need the template.yaml` or such other sentence that has similar meaning. However, in the current status, I got error below
![image](https://github.com/openvinotoolkit/training_extensions/assets/80735344/32b151ad-9601-43b1-a8c5-8bb66ddbb0ba)

I just experimented with `otx export`, so I'm not sure this issue could affects other CLI commands 

**Steps to Reproduce**

1. 
```
otx train otx/algorithms/detection/configs/instance_segmentation/resnet50_maskrcnn/template.yaml \
--train-data-roots tests/assets/car_tree_bug \
--val-data-roots tests/assets/car_tree_bug \
--workspace outputs \
params --tiling_parameters.enable_tiling 1
```
2.
```
otx export \
--test-data-roots tests/assets/car_tree_bug \
--load-weights outputs/outputs/latest_trained_model/models/weights.pth \
--output outputs/openvino
```

**Environment:**

- OS:  Ubuntu20.04
- Framework version:  Pytorch 1.13.1
- Python version: 3.10
- OpenVINO version: 2022.03
- CUDA/cuDNN version: 10.7
- GPU model and memory: RTX3090

**Comment by harimkang** [comment] 2023-05-15 06:30
I tried to do this in the latest develop.
First of all, the otx export part of the reproduction step is wrong: otx export requires a template.
So we need to either give `--workspace` separately, or on top of workspace, or give template args.
```
otx export \
--load-weights outputs/outputs/latest_trained_model/models/weights.pth \
--output outputs/openvino \
--workspace outputs

# or
cd outputs
otx export

# or
otx export \
otx/algorithms/detection/configs/instance_segmentation/resnet50_maskrcnn/template.yaml \
--load-weights outputs/outputs/latest_trained_model/models/weights.pth \
--output outputs/openvino
```
I believe the above is the appropriate command.

Also, when I followed your reproduction steps, I only got the output below.
![image](https://github.com/openvinotoolkit/training_extensions/assets/38045080/0185cec0-ff19-43e3-b229-0e9a1fd73e24)
If I remove `test-data-roots` here, it should say that the template is needed, but it's sending out a different message that doesn't make sense. I'll have to look into this and fix it.
![image](https://github.com/openvinotoolkit/training_extensions/assets/38045080/3a428024-759e-4fd7-9c12-4d3110d2c4dd)

However, I was still unable to reproduce the error message you attached.

**Comment by sungmanc** [comment] 2023-05-15 06:35
> I tried to do this in the latest develop. First of all, the otx export part of the reproduction step is wrong: otx export requires a template. So we need to either give `--workspace` separately, or on top of workspace, or give template args.

Yeah, I know the correct argument. We need to give proper error messages when users mis-input the arguments.

> Also, when I followed your reproduction steps, I only got the output below. ![image](https://user-images.githubusercontent.com/38045080/238260258-0185cec0-ff19-43e3-b229-0e9a1fd73e24.png) If I remove `test-data-roots` here, it should say that the template is needed, but it's sending out a different message that doesn't make sense. I'll have to look into this and fix it. ![image](https://user-images.githubusercontent.com/38045080/238260499-3a428024-759e-4fd7-9c12-4d3110d2c4dd.png)

Thanks very much !


> However, I was still unable to reproduce the error message you attached.

Ah, sorry, could you check with openvino.xml? In that case, you might get same error, I believe.
```
otx export \
--test-data-roots tests/assets/car_tree_bug \
--load-weights outputs/outputs/latest_trained_model/openvino/openvino.xml \
--output outputs/openvino
```

**Comment by harimkang** [comment] 2023-05-15 06:47
> > I tried to do this in the latest develop. First of all, the otx export part of the reproduction step is wrong: otx export requires a template. So we need to either give `--workspace` separately, or on top of workspace, or give template args.
> 
> Yeah, I know the correct argument. We need to give proper error messages when users mis-input the arguments.
> 
> > Also, when I followed your reproduction steps, I only got the output below. ![image](https://user-images.githubusercontent.com/38045080/238260258-0185cec0-ff19-43e3-b229-0e9a1fd73e24.png) If I remove `test-data-roots` here, it should say that the template is needed, but it's sending out a different message that doesn't make sense. I'll have to look into this and fix it. ![image](https://user-images.githubusercontent.com/38045080/238260499-3a428024-759e-4fd7-9c12-4d3110d2c4dd.png)
> 
> Thanks very much !
> 
> > However, I was still unable to reproduce the error message you attached.
> 
> Ah, sorry, could you check with openvino.xml? In that case, you might get same error, I believe.
> 
> ```
> otx export \
> --test-data-roots tests/assets/car_tree_bug \
> --load-weights outputs/outputs/latest_trained_model/openvino/openvino.xml \
> --output outputs/openvino
> ```


Did you mean otx eval ,not otx export?
I still can't reproduce it..

**Comment by sungmanc** [comment] 2023-05-15 06:55
I'll recheck my experimental arguments, sorry for confusing

**Comment by sungmanc** [comment] 2023-05-15 07:29
Sorry, I found that I misused the .xml file. Then, could you just check this ?
> If I remove test-data-roots here, it should say that the template is needed, but it's sending out a different message that doesn't make sense. I'll have to look into this and fix it.

**Comment by harimkang** [comment] 2023-06-19 08:54
My guess is that the merge of this PR (https://github.com/openvinotoolkit/training_extensions/pull/2251) should have resolved the issue.
Could you please double check and close it?

**Closed as completed** 2023-07-12 03:54 UTC
Labels: ENHANCE
