### ISSUE TITLE
training accuracy reported as 0.0 with CUB hierarchical label for the classification

### ISSUE THREAD

**Issue by yunchu** [open-edge-platform/training_extensions#2579] opened 2023-10-26 09:06 UTC
**Describe the bug**
Training accuracy reported as 0.0 with CUB hierarchical label for the classification
here is the part of regression_config.json for this testing
![image](https://github.com/openvinotoolkit/training_extensions/assets/5232387/ca59d79e-269c-49f0-9e03-1817a15175e1)

**Steps to Reproduce**

1. run classification regression TC 
```
$ CI_DATA_ROOT=/home/yunchule/data/ci_datasets/ tox -vvv -e tests-cls-py310-pt1 -- tests/regression/classification/test_classification.py::TestRegressionHierarchicalLabelClassification::test_otx_train[Custom_Image_Classification_EfficientNet-V2-S]
```
2. check the log
```
>       assert test_result["passed"] is True, test_result["log"]
E       AssertionError: [EfficientNet-V2-S] Performance: (0.0) < Criteria: (0.5418), threshold: 0.1.
E       assert False is True
```

**Environment:**

- OS: Ubuntu 20.04
- Framework version: Pytorch
- Python version: 3.10
- OpenVINO version: 2023.0
- CUDA/cuDNN version: 11.7
- GPU model and memory: 3090/24G

**Comment by wonjuleee** [comment] 2023-11-02 00:56
The problem was because of the hierarchical classification dataset generation from the original CUB data. Since CUB categories are composed of proper noun of birds, it is not appropriate to split the category names into hierarchies.

**Comment by yunchu** [comment] 2023-11-02 06:55
Thanks for your update @wonjuleee 
I will close this issue.

**Comment by goodsong81** [comment] 2023-11-10 07:02
Found root cause, and fixed in https://github.com/openvinotoolkit/training_extensions/pull/2626

**Closed as completed** 2023-11-10 07:29 UTC
Labels: BUG
